spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  output:
    ansi:
      enabled: always
  profiles:
    active: prod
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem